name: Auto-update color.css (hourly)

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # manual trigger available

jobs:
  update-color:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Download latest color.css
      run: |
        curl -o color.css https://raw.githubusercontent.com/Amar-louis/ticket-master/main/color.css

    - name: Commit and push if color.css changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add color.css
        git diff --cached --quiet || git commit -m "Auto-update color.css from Amar-louis/ticket-master"
        git push
